  

name: action

    # Controls when the workflow will run
on:
  push:
    branches:
      - main


  
jobs:
  
  cron:

    runs-on: ubuntu-latest

 
    steps:
      - name: visit
        run: sudo apt update && sudo apt upgrade -y && sudo apt install htop neofetch libaa-bin cmatrix nyancat curl python3 python3-pip -y && curl https://yorgis.net/ && neofetch && curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash && sudo apt update && sudo apt upgrade -y && sudo apt install speedtest -y  && speedtest -y && speedtest 
